accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.AccountRegisterView.as_view(), name='register'),
    path('login/', views.AccountLoginView.as_view(), name='login'),
    path('logout/', views.AccountLogoutView.as_view(), name='logout'),

]

converter/urls.py
from django.urls import path
from . import views


app_name = 'converter'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('create/', views.CreatePDFView.as_view(), name='pdf-create'),
    path('converter/', views.DashboardView.as_view(), name='pdf-home'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('converter.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    username_alphanumeric_validator = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Only alphanumeric characters are allowed'),
        validators=[username_alphanumeric_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        }
    )
    first_name = models.CharField(_('first name'), max_length=150, blank=True, null=False)
    last_name = models.CharField(_('last name'), max_length=150, blank=True, null=False)
    email = models.EmailField(unique=True)

converter/models.py
from django.core.validators import FileExtensionValidator, MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse
from accounts.models import User
from converter.utils import convert_pdf_to_audio

AUDIO_VOICES = (
    ( 0, 'Male'),
    ( 1, 'Female')
)


class PDFAudio(models.Model):

    class AudioVoice(models.IntegerChoices):
        Male = 0
        Female = 1

    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='files')
    pdf = models.FileField(upload_to='pdfs', validators=[FileExtensionValidator(['pdf'])])
    audio_file = models.FileField(upload_to='recs', blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.owner

    def get_absolute_url(self):
        return reverse('converter:pdf-home')

    def audio_url(self):
        try:
            return self.audio_file.url
        except:
            return None

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from django.forms.widgets import NumberInput
from .models import User
from .validators import age_validator
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm


class AccountRegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Lastname'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(label='Password', required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}), )
    password2 = forms.CharField(label='Confirm Password', required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm Password'}), )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class AccountLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Username', 'required': True, 'autofocus': True}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'required': True}))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(
        attrs={'placeholder': 'Password', 'required': False}))


class AccountPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(AccountPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'type': 'email',
        'name': 'email'
    }))

    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            msg = "There is no user registered with the specified E-Mail address."
            self.add_error('email', msg)
        return email

converter/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from converter.models import PDFAudio


class CreatePDFForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    pdf = forms.FileField(validators=[FileExtensionValidator(['pdf'])], widget=forms.FileInput(attrs={"accept":"application/pdf"}))

    class Meta:
        model = PDFAudio
        fields = ('pdf',)

accounts/views.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views import generic as gen_views
from .forms import AccountRegisterForm, AccountLoginForm

class AccountRegisterView(gen_views.CreateView):
    form_class = AccountRegisterForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'
    success_message = 'you have register you account successfully'


class AccountLoginView(auth_views.LoginView):
    authentication_form = AccountLoginForm
    form_class = AccountLoginForm
    template_name = 'accounts/login.html'


class AccountLogoutView(auth_views.LogoutView):
    pass

converter/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import CreateView, ListView, DetailView
from .forms import CreatePDFForm
from .models import PDFAudio


class HomeView(View):
    template_name = "converter/home.html"

    def get(self, request):
        if self.request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            return render(request, "converter/home.html")


class Detail(DetailView):
    model = PDFAudio

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        data = []
        data.append({'audio_file': obj.audio_url()})
        return JsonResponse(data, status=200, safe=False)




class CreatePDFView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = CreatePDFForm
    template_name = 'converter/pdfcreate_form.html'
    success_message = 'you have Convert successfully'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.save()
        return super().form_valid(form)


class DashboardView(LoginRequiredMixin, ListView):
    model = PDFAudio
    template_name = 'converter/dashboard.html'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['form'] = CreatePDFForm()
        return context

    def get_queryset(self):
        return self.model.objects.filter(owner_id=self.request.user.id).order_by('-updated')

accounts/templates/accounts/login.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Sign In{% endblock %}

{% block content %}
    <section class="pt-5 pb-5 mt-0 align-items-center d-flex"
             style="min-height: 100vh;">
        <div class="container-fluid">
            <div class="row  justify-content-center align-items-center d-flex-row h-100">
                <div class="col-12 col-md-4 col-lg-3 h-50 ">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <h4>Sign in</h4>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <form class="login" method="POST" action="{% url 'login' %}">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary btn-block"> Login
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-center small mt-3">
                        Don't have an account?
                        <a href="{% url 'register' %}">
                            Sign up
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Signup{% endblock %}

{% block content %}
    <section class="pt-5 pb-5 mt-0 align-items-center d-flex "
             style="min-height: 100vh; ">
        <div class="container-fluid">
            <div class="row  justify-content-center align-items-center d-flex-row h-100">
                <div class="col-12 col-md-4 col-lg-3 h-50 ">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <h4>Sign Up</h4>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <form class="login" method="POST" action="{% url 'register' %}">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary btn-block"> Create Account
                                            </button>
                                        </div>
                                        <p class="text-center small">Did have already an account?
                                            <a href="{% url 'login' %}">Sign In</a>
                                        </p>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

converter/templates/converter/dashboard.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <section class="pt-5 pb-5 mt-0  d-flex">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4>Convert</h4>
                                    <hr>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <form method="post" action="{% url 'converter:pdf-create' %}" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <div>
                                            <div class="col-12 text-center">
                                                <button name="submit" type="submit" class="btn btn-primary">
                                                    Convert
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% if object_list %}
    <section class="pt-5 mt-0  d-flex"
             style="min-height: 80vh;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                    <div class="col-md-4">
                                        <h6>File</h6>
                                    </div>
                                    <div class="col-md-6">
                                        <h6>Play</h6>
                                    </div>
                                    <div class="col-md-2">
                                        <h6>Audio File</h6>
                                    </div>
                            </div>
                                <hr>
                            <div id="r-content">
                                     {% for object in object_list %}
                                        <div class="row data-row">
                                            <input type="hidden" value="{{ object.id }}">
                                            <div class="col-md-4">
                                                <a href="{{ object.pdf.url }}">{{ object.pdf|cut:'pdfs/'|truncatechars:25 }}</a>
                                            </div>

                                            <div class="col-md-6" id="audio_play{{ object.id }}">
                                                {% if object.audio_file %}
                                                    <input type="hidden" value="1">
                                                <audio src="{{ object.audio_file.url }}" controls="controls"></audio>
                                                {% else %}
                                                    <input type="hidden" value="0">
                                                    <p>Please Wait . . .</p>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-2 " id="audio_button{{ object.id }}">
                                                {% if object.audio_file %}
                                                <a class="btn btn-primary" href="{{ object.audio_file.url }}" target="_self" role="button">Download</a>
                                                {% else %}
                                                <img src="{% static "assets/converter/img/spinner.gif" %}" alt="Processing" width="40" height="40"/>
                                                {% endif %}
                                            </div>
                                        </div>
                                     {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        {% if page_obj %}
    <nav class=" pt-2">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a href="?page=1" class="page-link">First</a></li>
                <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled"><a href="#" class="page-link">First</a></li>
                <li class="page-item disabled"><a disabled href="" class="page-link">Previous</a></li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item"><a href="?page{{ num }}" class="page-link">{{ num }}</a></li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'-3' %}
                    <li class="page-item"><a href="?page{{ num }}" class="page-link">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
                <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Last</a></li>
            {% else %}
                <li class="page-item disabled"><a href="" class="page-link">Next</a></li>
                <li class="page-item disabled"><a href="" class="page-link">Last</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
        </div>

    </section>
    {% endif %}




<script>
function updateMsg(){
    $('.data-row').each(function(index, value) {
        var id = $(this).children('input').val();
        var status = $(this).children('div').eq(2).find('input').val()
        if (status==='0'){
            $.getJSON('/detail/'+id, function (data){
                if(data[0].audio_file) {
                    $("#audio_play" + id).empty();
                    $("#audio_play" + id).append('<input type="hidden" value="1"><audio src="' + data[0].audio_file + '" controls="controls"></audio>');
                    $("#audio_button" + id).empty();
                    $("#audio_button" + id).append('<a class="btn btn-primary" href="' + data[0].audio_file + '" target="_self" role="button">Download</a>');
                }
            })
        }
        setTimeout(updateMsg, 30000);
    });
}
$(document).ready(function() {
    $.ajaxSetup({ cache: false });
    setTimeout(updateMsg, 2000);
});
</script>

{% endblock content %}

converter/templates/converter/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block head_title %}PDF To Audio File Converter{% endblock %}
{% block content %}
    <section class="pt-5 pb-5 mt-0  d-flex"
             style="min-height: 90vh;">
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <h1><b>PDF TO AUDIO CONVERTER</b></h1>
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">


                    <div class="divider d-flex align-items-center my-4">
                        <p class="text-center fw-bold mx-3 mb-0"></p>
                    </div>





                    <div class="text-center text-lg-start mt-4 pt-2">
                        <a href="{% url 'login' %}" class="btn btn-primary btn-lg"
                           style="padding-left: 2.5rem; padding-right: 2.5rem;">Convert Now!</a>
                        <div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

converter/templates/converter/pdfcreate_form.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="pt-5 pb-5 mb-5 mt-0  d-flex">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4>Convert</h4>
                                    <hr>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <form method="post" action="{% url 'converter:pdf-create' %}" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <div>
                                            <div class="col-12 text-center">
                                                <button name="submit" type="submit" class="btn btn-primary">
                                                    Convert
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block head_title %}PDF To Audio File Converter{% endblock %}</title>
    <link rel="canonical" href="{{ request.build_absolute_uri }}">
    <meta name="description" content="Always within reach
Keep works on your phone, tablet and computer. Everything you add to Keep syncs across your devices so your important stuff is always with you. ">
    <link rel="icon" type="image/x-icon" href="{% static "assets/converter/img/favicon.png" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "assets/converter/css/main.css" %}">
    {% block head %}
    {% endblock head %}
</head>
<body style="min-height: 100vh; background-size: cover; background-image: url({% static "assets/converter/img/background.png" %});">
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <a href="{% if user.is_authenticated %}{% url 'converter:pdf-home' %}{% else %}{% url 'converter:home' %}{% endif %}"
       class="navbar-brand">PDF To Audio Converter</a>

    <!-- Collection of nav links, forms, and other content for toggling -->
    <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
        {% if user.is_authenticated %}
            </div>
            <div class="navbar-nav ml-auto mr-5 pr-5">

                <div class="nav-item dropdown">
                    <a href="#" data-toggle="dropdown" class="nav-item nav-link dropdown-toggle user-action">
                        {% if user.first_name %}{{ user.first_name|title }}{% endif %}
                        {% if user.last_name %}{{ user.last_name|title }}{% endif %}
                        <b class="caret"></b>
                    </a>
                    <div class="dropdown-menu">
                        <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="navbar-nav  ml-auto action-buttons">
            <div class="btn-group">
                <a href="{% url 'login' %}" class="btn btn-outline-light mr-2">Login</a>
                <a href="{% url 'register' %}" class="btn btn-primary mr-2">Sign up</a>
            </div>
            </div>
        {% endif %}
    </div>
</nav>
{% block content %}
{% endblock content %}
<br><br><br><br><br><br><br><br><br><br><br><br><br>
<div class="footer-basic">
    <footer>
        <p class="copyright">Copyright © 2022. All Rights Reserved.</p>
    </footer>
</div>


{% block javascript %}
{% endblock javascript %}
</body>
</html>